server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootx-platform?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        # 重试机制
        retry:
          enabled: true
          max-attempts: 5
  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
  quartz:
    job-store-type: jdbc
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: true
            misfireThreshold: 60000
            clusterCheckinInterval: 10000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

# 开发时显示debug日志
logging:
  level:
    cn.bootx.**: debug
# 项目配置
bootx:
  common:
    swagger:
      enabled: true
      version: 2.0.0
      title: bootx-platform平台单体版
      description: bootx平台单体版
      # 多模块扫码
      base-packages:
        iam: cn.bootx.iam
        baseapi: cn.bootx.baseapi
        notice: cn.bootx.notice
        goods: cn.bootx.goods
        payment: cn.bootx.payment
        sales: cn.bootx.sales
        order: cn.bootx.order
        starter: cn.bootx.starter
  starter:
    auth:
      default-password: 123456
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/jmreport/**'
        - '/doc.html'
        - '/webjars/**'
        - '/swagger-resources/**'
        - '/token/**'
        - '/mobile/**'
        - '/css/**'
        - '/**'

