filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/logs/platform/*.json
# 输出到es
output.elasticsearch:
  hosts: http://localhost:9200
  # index: "%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
  index: "bootx-platform-logs"
# 设置
setup:
# 自定义索引的话必须设置
  template:
    name: "filebeat"
    pattern: "filebeat-*"
  ilm.enabled: false
processors:
  - decode_json_fields:
      fields: ['message'] #要进行解析的字段
      target: "" #json内容解析到指定的字段，如果为空（“”），则解析到顶级结构下
  - drop_fields:
      fields: ["log","ecs","agent","input","@metadata","message"] #删除无用的字段
